version: '2'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
      - MYSQL_ROOT_HOST=%
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    networks:
      - spring
  app:
    depends_on:
      - db
    restart: on-failure
    build: app/
    ports:
      - "8080:8080"
    networks:
      - spring
    links:
      - db
networks:
  spring:
    driver: bridge
